---
title: "muerte-red"
output: html_notebook
---
```{r}
require(shiny)
require(visNetwork)
library(markdown)
#shiny::runApp(system.file("shiny", package = "visNetwork"))
# Define UI for app that draws a histogram ----
ui <- fluidPage(style="padding-top: 0px;",
    visNetworkOutput("network",height="1000"),
  absolutePanel(
    top = 20, left = 20, width = 200,
    draggable = TRUE,
    wellPanel(
      selectInput(inputId="select", label = h4("Select stanza"), 
          choices = list("Stanza 1" = 1, "Stanza 2" = 2, "Stanza 3" = 3, "Stanza 4" = 4,
                        "Stanza 5" = 5, "Stanza 6" = 6, "Stanza 7" = 7,"Stanza 8" = 8,
                        "Stanza 9" = 9, "Stanza 10" = 10, "Stanza 11" = 11, "Stanza 12" = 12,
                        "Stanza 13" = 13,"Stanza 14" = 14, "Stanza 15" = 15, "Stanza 16" = 16, "Whole poem" = 0),
          selected = 1),
      checkboxInput(inputId="nodetype","All Nodes", value = TRUE),
      checkboxInput(inputId="soundon","With Sound", value = FALSE)
    ),
    style = "opacity: 0.92"
  )
)


# Define server logic required to draw network
server <- function(input, output, session) {
  output$network <- renderVisNetwork({
    plot.stanza(as.numeric(input$select)-1, input$nodetype, input$soundon)
  })
}

shinyApp(ui = ui, server = server)
runApp("my_app")
```

```{r}

plot.stanza <- function(n, a, s) {
    INDEX=toString(n)
    if(INDEX=="-1") {
        nodes <- read.csv("~/muerte-red/narciso/nodes.csv", header=T, as.is=T)
    links <- read.csv("~/muerte-red/narciso/edges.csv", header=T, as.is=T)
        
    } else {
      if(s) {
        links <- read.csv(paste(paste("~/muerte-red/narciso/edges-sound-",INDEX,sep=""),".csv",sep=""), header=T, as.is=T) 
        nodes <- read.csv("~/muerte-red/narciso/nodes-2.csv", header=T, as.is=T)
      } else {
          if(a) {
          nodes <- read.csv("~/muerte-red/narciso/nodes.csv", header=T, as.is=T)
        } else {
          nodes <- read.csv(paste(paste("~/muerte-red/narciso/nodes-",INDEX,sep=""),".csv",sep=""), header=T, as.is=T)
        }
        links <- read.csv(paste(paste("~/muerte-red/narciso/edges-",INDEX,sep=""),".csv",sep=""), header=T, as.is=T)
      }
    }
       
    
    library("igraph")
    net <- graph_from_data_frame(d=links, vertices=nodes, directed=T) 
    library("visNetwork") 
    
    vis.nodes <- nodes
    vis.links <- links
    
    vis.nodes$shape  <- "dot"  
    vis.nodes$shadow <- FALSE # Nodes will drop shadow
    #vis.nodes$title  <- vis.nodes$media # Text on click
    vis.nodes$label  <- vis.nodes$id # Node label
    vis.nodes$label.cex  <- 50 # Node label
    vis.nodes$title  <- vis.nodes$weight
    vis.nodes$size   <- 15+(60*log10((vis.nodes$weight-1)/20*2+1))# Node size
    vis.nodes$borderWidth <- .5 # Node border width
    
    #vis.nodes$color.background <- c("slategrey", "tomato", "gold")[nodes$id]
    vis.nodes$color.border <- "black"
    vis.nodes$color.highlight.background <- "orange"
    vis.nodes$color.highlight.border <- "red"
    
    #edge properties
    #vis.links$width <- 1+links$weight/8 # line width
    vis.links$color <- c("navy","navy","navy", "orange")[links$type] # line color  
    vis.links$edge.arrow.mode <- c(2,2,2,3)[links$type]
    vis.links$arrows <- "middle"
    vis.links$smooth <- TRUE    # should the edges be curved?
    vis.links$shadow <- FALSE    # edge shadow
    vis.links$dashes <- c(FALSE, TRUE, TRUE, TRUE)[links$type]
    if(INDEX=="-1") {
        visnet <- visNetwork(vis.nodes, vis.links, width="100%", height="1100px") %>% visPhysics(stabilization = FALSE)
    } else {
        visnet <- visNetwork(vis.nodes, vis.links, width="100%", height="1000px") %>% visPhysics(stabilization = FALSE)
    }
    return(visnet)
   
}

#plot.stanza(1)
#plot.stanza(2)
#plot.stanza(3)
#plot.stanza(4)
#plot.stanza(6)
##plot.stanza(5)
#plot.stanza(7)
#plot.stanza(8)
#plot.stanza(9)
#plot.stanza(10)
#plot.stanza(11)
#plot.stanza(12)
#plot.stanza(13)
#plot.stanza(14)
#plot.stanza(-1)
```

```{r}
